### PR TITLE
Fixed Tooltip on mobile

### LINKED ISSUE #121: Tax deduction tooltip does not work on mobile
It is not possible to hover the question mark on mobile.

### PR DESCRIPTION
**Pull request by HEYROCKME**
Resolves #121

### CODE REVIEW

**Comment by JorgenLjones** [comment]
Good catch Alwin (@HEYROCKME)! @philiphand kan du haste denne igjennom? :-)

**Comment by philiphand** [comment]
Looks great!

Just wanted to make sure that it's intended that the tooltip only activates on click, but no longer on hover (with a mouse) like it used to?

Also, there is a bigger gap between the text and the tooltip icon than before, is this also intended?
image
image

**Comment by JorgenLjones** [comment]
Can it activate both on hover and on click? That seems to be best
@HEYROCKME

**Comment by mortenkjelling** [comment]
From an accessibilty standpoint click is the better option, because it supports keyboard navigation. Hoverver (hø-hø), I adde hover as well now.
The bigger visual gap was to make it easier to tap the icon instead of the label, so yes it is intentional, but was not work as expected, so I`m gonna have a look to tweak that as well.

**Comment by philiphand** [comment]
Perfect!

**Pull request merged**
